### ISSUE TITLE
Legacy subgrid width

### ISSUE THREAD

**Issue by Wooya** [free-jqgrid/jqGrid#225]
I've upgraded jqGrid to newest 4.13.3-pre and noticed that legacy subrid takes all available horizontal space in row which looks not good in grid without cols stretching:

![image](https://cloud.githubusercontent.com/assets/541588/14733968/54c2a3b6-0867-11e6-82b4-ccc62ae762fe.png)

This issue affects also subGridModel colums widths which simlpy not respected.

My proposal is to add in `.ui-jqgrid-legacy-subgrid` class `width: auto;`, then legacy subgrid looks nice (subGridModel columns widths are also respected):

![image](https://cloud.githubusercontent.com/assets/541588/14734034/c78cdeac-0867-11e6-9d92-07cd200f3436.png)

**Comment by OlegKi** [comment]
Thank you for reporting the problem, but I would like to know more detail. You wrote that you can see the problem after upgrading jqGrid to newest 4.13.3-pre. Which version of free jqGrid you used before? Could you provide the demo which could be used to reproduce the problem? I made some tests and [the CSS rule](https://github.com/twbs/bootstrap/blob/v3.3.6/dist/css/bootstrap.css#L2264-L2268) of Bootstrap
```css
.table {
  width: 100%;
  max-width: 100%;
  margin-bottom: 20px;
}
```
is applied on the legacy subgrid.
The most interesting thing for me is why any changes exist in jqGrid to newest (which one?) 4.13.3-pre. I'd like to locale and analyse the problem before applying any changes.

**Comment by Wooya** [comment]
Of course. Here're samples.

1. jqGrid v4.13 (old one which I used before)
[https://skrj.plk-sa.pl/mvc/jqgrid2](url)

2. jqGrid v4.13.3 (latest one)
[https://skrj.plk-sa.pl/mvc/jqgrid](url)

Please expand subgrids to see the effect.

**Comment by OlegKi** [comment]
First of all you compare **very old** v4.13 which don't contains any support of legacy subgrid for Bootstrap. I included the corresponding fixes *later* after your bug reports.

If I correctly understand your suggestion, that you want that subgrid will **be don't scratched**. You want that `width: 100%;` will be *not applied*. The usage of `width: auto;` in the case seems a little misunderstandable for me. We use `table-layout: fixed` (like for all other tables):
```
.ui-jqgrid .ui-subgrid table {
    table-layout: fixed;
}
```
Thus the widths of *first row* of the grid (which is `thead>tr` in the case) should define the widths of all columns. It works with almost **any** value of `width` applied on the corresponding table. I use now `width: 1px` for all tables in such case. You can open developer tools and to add inline `style="width: 1px;"` to see results.

If I correctly understand your suggestion than I can add setting of `style="width: 1px;"` in the code which generates subgrid to fix the problem. Should it solve the problem which you report? If you confirm this then I'll make the corresponding changes in the code of free jqGrid.

**Comment by Wooya** [comment]
Hi Oleg!

Thanks for response. Seems that style width: 1px fixes the problem... almost :)

take a look at legacy grid after add suggestyed setting:
![image](https://cloud.githubusercontent.com/assets/541588/14739639/23e3fa0c-0889-11e6-8d73-3404406d9081.png)

If width of the cell is less than width of the content, content of one cell overlaps other cell. I think elegant solution is to add text ellipsis to each cell:

`.ui-jqgrid-legacy-subgrid th, .ui-jqgrid-legacy-subgrid td {
    text-align:left; 
    width: 100%; 
    overflow: hidden; 
    white-space: nowrap; 
    text-overflow: ellipsis;
}`

then subgrid looks like below:
![image](https://cloud.githubusercontent.com/assets/541588/14739798/4d5aafba-088a-11e6-9cbb-f5f2a6c130b4.png)

Another thing with ellipsis is to add hint to each cell like normal jqGird do.

Of course those above are only my suggestions. If you want, I'll implement my ideas and I'll send a pull request.

**Comment by OlegKi** [comment]
Thank you! I see that problem, but the usage of `text-overflow: ellipsis;` can have some other disadvantageous and it's another way as in the main grid. I think that it's better just to extent [the rule](https://github.com/free-jqgrid/jqGrid/blob/v4.13.2/css/ui.jqgrid.css#L226-L231) and [this one](https://github.com/free-jqgrid/jqGrid/blob/v4.13.2/css/ui.jqgrid.css#L377-L389) to be applied on the legacy subgrid too:
```css
.ui-jqgrid-labels .ui-th-column-header,
.ui-jqgrid .ui-jqgrid-labels th.ui-th-column,
.ui-jqgrid .ui-jqgrid-legacy-subgrid .ui-th-subgrid {/* the line is added*/
	overflow: hidden;
	white-space: nowrap;
	text-align: center;
}
```
and
```css
.ui-jqgrid tr.jqgrow > td,
.ui-jqgrid tr.jqgroup > td,
.ui-jqgrid tr.jqfoot > td,
.ui-jqgrid tr.ui-subgrid > td,
.ui-jqgrid tr.ui-subtblcell > td {/* the line is added*/
	overflow: hidden;
	white-space: pre;
	vertical-align: middle;
	text-align: center;
	height: 22px;
	border-top: 0 none;
	border-bottom-width: 1px;
	border-bottom-style: solid;
}
```
One can still overwrite any from the styles and to use `text-overflow: ellipsis;` for example.

Do you see some other problems?
