### ISSUE TITLE
Sort icons misaligned with current jQuery UI themeroller themes (as used in jQuery UI 1.12.x)

### ISSUE THREAD

**Issue by matt-hoskins** [free-jqgrid/jqGrid#270]
Hi,

Firstly, thanks for developing a free version of jqGrid! :)

I'm trying to use free jqGrid in combination with jQuery UI 1.12.1 and a theme included with it generated with the latest themeroller. The sort icons are misaligned, alas. This seems to be due to changes that jQuery have made in the css for the icons. 

In jQuery UI 1.11.x and 1.10.x, with the themes being generated by themeroller at the time, the css for .ui-icon was:
```css
.ui-icon {
	display:block;
	text-indent:-99999px;
	overflow:hidden;
	background-repeat:no-repeat
}
```

In 1.12.x and the current themeroller it's now:
```css
.ui-icon {
	display: inline-block;
	vertical-align: middle;
	margin-top: -.25em;
	position: relative;
	text-indent: -99999px;
	overflow: hidden;
	background-repeat: no-repeat;
}
```
In the current version of free jqGrid you override the "display" to make it "block" but don't touch the "margin-top", hence it appearing as in the first attached image.

![freejqgrid-jqueryui_1_12_alignment_issue](https://cloud.githubusercontent.com/assets/5127538/18781155/87f082dc-8178-11e6-9086-5ab37ea4e4ee.png)

Just overriding the margin-top to be 0px for just these jqgrid icons (which is just the browser default margin-top it had with prior versions of jQuery UI themes) seems to do the job and should still be compatible with prior versions of jQuery UI themes. i.e. adding margin-top 0px to this:
```css
.ui-jqgrid .s-ico > .ui-grid-ico-sort.ui-icon {
	width: 12px;
	margin-top:  0px; /* Fix for jQuery UI 1.12.x themeroller changes in icon styling */
}
```
I've attached a second image showing the results of me making the change.

![freejqgrid-jqueryui_1_12_alignment_issue-topmarginfix](https://cloud.githubusercontent.com/assets/5127538/18781173/9de2b2f4-8178-11e6-8129-60292f1e49ab.png)

Unfortunately that's still not quite perfect as sadly the two icons are not aligned horizontally. The reason for the horizontal alignment not being correct is that there was a long standing bug in the jQuery UI themes with the sprite image whereby the south icon was one pixel misaligned compared to the north. (https://bugs.jqueryui.com/ticket/4447) And it seems that jqGrid compensates for this by using slightly different left margins for the asc and desc icons.

In the latest themeroller themes they haven't fixed the image, but they do compensate for the offset in the sprite image by changing the background position slightly for the south icon. So old themeroller had this:
```css
.ui-icon-triangle-1-s {
    background-position: -64px -16px;
}
```

And new themeroller has this:
```css
.ui-icon-triangle-1-s {
    background-position: -65px -16px;
}
```

The fix for jqGrid would be to make the margin-left the same for both asc and desc icons. And indeed if I change the following to be -3px instead of -4px you get the final image I've attached:
```css
.ui-jqgrid .s-ico > .ui-icon-desc.ui-icon.ui-sort-ltr {
    margin-left: -3px;
}
```
![freejqgrid-jqueryui_1_12_alignment_issue-bothmarginfix](https://cloud.githubusercontent.com/assets/5127538/18781178/a828b132-8178-11e6-9311-2c3996a7034c.png)

However of course if you make this change then anyone using an older themeroller theme would then have them misaligned instead, so there's no simple solution to make that horizontal alignment be correct with both old themeroller and new themeroller themes. I guess it would have to be a case of having it correct for either the old or new themeroller type and providing a css override for users to include in their stylesheet to fix it if they have the other themeroller type.

Kind regards,
Matt
