### ISSUE TITLE
Minimal grid width issue

### ISSUE THREAD

**Issue by cosinus90** [free-jqgrid/jqGrid#340]
When column are auto-resized and If columns happen to be shorter then grid caption and navigation block - caption get wrapped and navigation get cut. 
Here is the code
https://codepen.io/zzmaster/embed/pwvWwV

It woul
![clipboard01](https://cloud.githubusercontent.com/assets/16591556/26789084/0e7c7892-49c4-11e7-8ec3-bdbc17bb06b1.jpg)
d be great if there will be minimal width calculated from width of cation and navigation and auto resize should enlarge columns proportionally.

**Comment by OlegKi** [comment]
Wrapping of caption is practical thing in many scenarios. Thus one can't use width of cation as minimal width of the grid in the common case.

One can get good results by adding simple CSS rules like
```css
.ui-jqgrid,
.ui-jqgrid>.ui-jqgrid-view,
.ui-jqgrid>.ui-jqgrid-view>.ui-jqgrid-titlebar,
.ui-jqgrid>.ui-jqgrid-view>.ui-jqgrid-toppager,
.ui-jqgrid>.ui-jqgrid-view>.ui-jqgrid-hdiv,
.ui-jqgrid>.ui-jqgrid-view>.ui-jqgrid-bdiv,
.ui-jqgrid>.ui-jqgrid-view .ui-jqgrid-btable,
.ui-jqgrid>.ui-jqgrid-pager {
  min-width: 340px;
}
```
which not changes the width of columns, but  which still increase the width of the grid.
See https://codepen.io/anon/pen/BZjOmO

Alternatively one can use the code like the following as a workaround
```JavaScript
$grid.on("jqGridResetFrozenHeights", function () {
    var width = $grid.jqGrid("getGridParam", "width"), minWidth = 340;

    if (width < minWidth) {
        $grid.jqGrid("setGridWidth", minWidth);
    }
});
```
See https://codepen.io/anon/pen/dRGqGO
